### ISSUE TITLE
Fix the tests in gocelery

### ISSUE THREAD

**Issue by vedhavyas** [centrifuge/gocelery#11]
In-memory and Rabbitmq tests are failing

**Comment by vimukthi-git** [comment]
I will pick this up when working on gocelery tasks for next milestone, putting back to backlog for now.

**Comment by vedhavyas** [comment]
Removed the blockers as the failing tests are not related to the retry or delay support

**Comment by vimukthi-git** [comment]
it's is a blocker as we can't verify on travis :), Please fix if you want to work on tasks, We can't merge anything with confidence.

cc @lucasvo
